import { test } from '@/public/png/review/before-after/index';

export const reviewData = [
  {
    id: 1,
    searchKey: '박상우트레이너2호점부천범안점',
    images: [test],
    title: '박*우 회원님',
    tag: '바디프로필',
    center: '2호점 부천 범안점',
    trainer: '박상우 트레이너',
    clientReview: '',
    trainerReview: '',
  },
  {
    id: 2,
    searchKey: '남건우트레이너1호점안산신길점',
    images: [test],
    title: '김*진 회원님',
    tag: 'PT후기',
    center: '1호점 안산 신길점',
    trainer: '남건우 트레이너',
    clientReview: '',
    trainerReview: '',
  },
  {
    id: 3,
    searchKey: '김도윤트레이너4호점구로천왕점',
    images: [test],
    title: '진*민 회원님',
    tag: '바디챌린지',
    center: '4호점 구로 천왕점',
    trainer: '김도윤 트레이너',
    clientReview: '',
    trainerReview: '',
  },
  {
    id: 4,
    searchKey: '남건우트레이너1호점안산신길점',
    images: [test],
    title: '김*우 회원님',
    tag: '바디프로필',
    center: '1호점 안산 신길점',
    trainer: '남건우 트레이너',
    clientReview: '',
    trainerReview: '',
  },
];
