import {
  center8_1,
  center8_2,
  center8_3,
  center8_4,
  trainer1_1,
  trainer2_1,
  trainer3_1,
  trainer4_1,
  trainer4_2,
  trainer5_1,
  trainer5_2,
  trainer6_1,
  trainer6_2,
  trainer7_1,
  trainer7_2,
  trainer8_1,
  trainer8_2,
} from '@/public/png/center/center8/index';

const center8 = {
  centerName: '8호점 군포 산본점',
  address: '경기 군포시 고산로 691 도율빌딩 5층',
  phone: '0507-1390-3375',
  images: [center8_1, center8_2, center8_3, center8_4],
  operatingTime: `
평일 : 06:00 ~ 24:00
주말 및 공휴일 : 10:00 ~ 18:00
공휴일 휴무 : 별도 공지
`,
  trainers: [
    {
      id: 1,
      name: '김대환 트레이너',
      career: [
        'Mr. 경남 -90kg 3위',
        'Mr. 창원 -90kg 3위',
        '경남도민체전 +90kg 1위',
        'nica 클래식피지크 1위',
        'NABA korea 보디빌딩 top5',
        'NPC 찬클래식 보디빌딩 5위',
        'PCA korea 보디빌딩 +85kg 1위',
      ],
      tags: [
        '생활스포츠지도사 2급(보디빌딩)',
        'NASM-CPT 미국 공인 퍼스널 트레이너 자격',
        'CES KOREA 대한교정운동전문가',
        'kacep 대한운동사학회 정회원',
      ],
      images: [trainer1_1],
    },
    {
      id: 2,
      name: '정재호 트레이너',
      career: [
        '남스점 6호점 점장',
        '전) 남스점 2호점 팀장',
        '전) 글로리 휘트니스 트레이너',
        'NPC 보디빌딩 3위',
        'NPC 피지크 3위',
      ],
      tags: [
        '생활스포츠지도사 2급(보디빌딩)',
        '운동처방사 2급',
        'IKA 케틀벨 트레이닝 Lv.2',
        '저스트핏 EMS트레이닝 자격 수료',
        '불가리안백 마스터',
        '블랙롤 근막이완 자격증',
        'CES PERSONAL TRAINING',
      ],
      images: [trainer2_1],
    },
    {
      id: 3,
      name: '신용재 트레이너',
      career: [
        '남스짐 4호점 점장',
        '전) 남스짐 2호점 트레이너',
        '21` WNPC성남 스포츠모델 입상',
      ],
      tags: [
        '명지대학교 체육학부 졸업',
        'NASM-CPT 미국 공인 퍼스널 트레이너 자격',
        '생활스포츠지도사 2급(보디빌딩)',
        '운동처방사 2급',
        '기초, 기능해부학 과정 수료',
        'MES 운동처방사 교육 수료',
        '소도구 트레이닝 Lv.2 수료',
      ],
      images: [trainer3_1],
    },
    {
      id: 4,
      name: '임시영 트레이너',
      career: [
        '남스짐 8호점 마스터 트레이너',
        '전) 바디채널 트레이너',
        '전) 자메이카 휘트니스 트레이너',
        '전) 휘트니스 메가짐 트레이너',
      ],
      tags: [
        '용인대학교 유도학과 졸업',
        'NASM-CPT 미국 공인 퍼스널 트레이너 자격',
        'NASM 스포츠 영양 코치 자격',
        'BASTM technique(연부조직가동술) 교육 수료',
        'BAREFOOT Rehab specialist 재활전문가 코스 Lv.1 수료',
        '대한심폐소생협회 CPR 교육 수료',
        '유도 4단',
        '검도 2단',
        '합기도 2단',
      ],
      images: [trainer4_1, trainer4_2],
    },
    {
      id: 5,
      name: '김재이 트레이너',
      career: ['남스짐 8호점 트레이너', '전) 남스짐 6호점 트레이너'],
      tags: [
        '남스짐 아카데미 교육 수료',
        '운동해부학 교육 수료',
        '불가리안백 교육 수료',
        '소도구 트레이닝 교육 수료',
        '보행평가 교육 수료',
      ],
      images: [trainer5_1, trainer5_2],
    },
    {
      id: 6,
      name: '유민우 트레이너',
      career: ['남스짐 8호점 트레이너'],
      tags: ['생활스포츠지도사 2급(보디빌딩)'],
      images: [trainer6_1, trainer6_2],
    },
    {
      id: 7,
      name: '이규호 트레이너',
      career: [
        '남스짐 8호점 트레이너',
        '전) 애비뉴 PT센터 트레이너',
        '태권도 사범',
      ],
      tags: [
        '생활스포츠지도사 2급(보디빌딩)',
        'FISAF KOREA MEDICAL TRAINING',
        '청춘웨이트 교육 수료',
        'kata 스포츠 테이핑&마사지 교육 수료',
        '태권도 4단',
        '용무도 1단',
      ],
      images: [trainer7_1, trainer7_2],
    },
    {
      id: 8,
      name: '전봉진 트레이너',
      career: [
        '초/중/고 축구선수 출신',
        '우석대학교 체육학과',
        '전) 원포올 PT스튜디오 트레이너',
        '현) 남스짐 8호점 트레이너',
      ],
      tags: [
        '생활스포츠지도사 2급(보디빌딩)',
        '국제 독일 블랙롤 자격증',
        'CES-PTC(퍼스널 트레이닝) 자격증',
        'Heart Rate Trainer 자격 수료',
        'TFT 트렌스핏 트레이닝 자격 수료',
        '브라이언박 테크니컬 스트레칭 자격 수료',
        '기능 해부학 길잡이 15기 수료',
        '근골격계 통증 재활 자격 수료',
        'TFT 트랜스핏 트레이닝 자격 수료',
      ],
      images: [trainer8_1, trainer8_2],
    },
  ],
  kakaoTalkUrl: 'https://pf.kakao.com/_STxcrb',
  naverPlaceUrl:
    'https://map.naver.com/v5/entry/place/1136567577?c=14129897.3264950,4491016.1690441,15.96,0,0,0,dh&isCorrectAnswer=true',
};

export default center8;
