import {
  center1_1,
  center1_2,
  center1_3,
  center1_4,
  trainer1_1,
  trainer1_2,
  trainer2_1,
  trainer2_2,
  trainer3_1,
  trainer3_2,
  trainer4_1,
  trainer5_1,
  trainer5_2,
  trainer6_1,
  trainer7_1,
  trainer8_1,
  trainer8_2,
  trainer9_1,
  trainer9_2,
} from '@/public/png/center/center1/index';

const center1 = {
  centerName: '1호점 안산 신길점',
  address: '경기 안산시 단원구 새뿔길 48 월산빌딩 지하 1층, 3층',
  phone: '0507-1388-3413',
  images: [center1_1, center1_2, center1_3, center1_4],
  operatingTime: `
평일 : 09:00 ~ 23:30
주말 및 공휴일 : 10:00 ~ 18:00
정기휴무 : 매주 일요일
공휴일 휴무 : 별도 공지
`,
  trainers: [
    {
      id: 1,
      name: '김현중 트레이너',
      career: [
        '남스짐 1호점 트레이너',
        '전) 나인짐 트레이너',
        '전) 건강해짐 트레이너',
      ],
      tags: [
        '생활스포츠지도사 2급(보디빌딩)',
        'BLACK ROLL 자격증',
        'TFT 자격증',
        '소도구 트레이닝 교육 이수',
        'FISAF KOREA 자격증',
        'Functional Taping 자격증',
      ],
      images: [trainer1_1, trainer1_2],
    },
    {
      id: 2,
      name: '손석환 트레이너',
      career: [
        '남스짐 1호점 트레이너',
        '전) 바디스타 트레이너',
        '전) 애플짐 트레이너',
      ],
      tags: [
        '생활스포츠지도사 2급(보디빌딩)',
        '스포츠 마사지 교육 이수',
        '소도구 트레이닝 교육 이수',
        'FISAF KOREA 자격증',
        'Functional Taping 자격증',
      ],
      images: [trainer2_1, trainer2_2],
    },
    {
      id: 3,
      name: '김지훈 트레이너',
      career: [
        '남스짐 1호점 마스터 트레이너',
        '전) 유니크짐 트레이너',
        '전) 바디휘트니스 트레이너',
      ],
      tags: [
        '생활스포츠지도사 2급(보디빌딩)',
        'FISAF KOREA PERSONAL TRAINING',
        'FISAF KOREA MEDICAL TRAINING',
        'CES KOREA 대한교정운동전문가',
        'KT TAPE 자격',
        'AKF KETTLEBELL LEVEL 1,2,3',
        'NASM CPT',
        'WNGP 보디빌딩 동메달',
        '글라스톤 교육 이수',
        '스포츠 마사지 교육 이수',
        '소도구 트레이닝 교육 이수',
      ],
      images: [trainer3_1, trainer3_2],
    },
    {
      id: 4,
      name: '황재민 트레이너',
      career: [
        '남스짐 1호점 트레이너',
        '전) 바디스타 휘트니스 트레이너',
        '전) 새마을 휘트니스 트레이너',
      ],
      tags: [
        '생활스포츠지도사 2급(보디빌딩)',
        '명지대학교 체육학부 졸업',
        'FISAF KOREA PERSONAL TRAINING',
        'FISAF KOREA MEDICAL TRAINING',
        'CES KOREA 교정운동학',
        'KT TAPE 자격',
        'AKF KETTLEBELL LEVEL 1,2,3',
        'WNGP 주최 대회 스포츠모델 TOP 6',
        '글라스톤 교육 이수',
      ],
      images: [trainer4_1],
    },
    {
      id: 5,
      name: '박진희 트레이너',
      career: [
        '남스짐 1호점 트레이너',
        '전) 퍼펙트바디 휘트니스 GX 팀장',
        '전) 경수중학교 헬스&다이어트반 강사',
        '전) 대림휘트니스 트레이너 및 GX 팀장',
      ],
      tags: [
        '생활스포츠지도사 2급(보디빌딩)',
        '관동대학교 사회체육학과 졸업',
        'CES PERSONAL TRAINING',
        'NASM CPT',
        '유아체육지도자',
        '운동처방사',
        'KT TAPE 자격',
        '글라스톤 교육 이수',
        '스포츠 마사지 교육 이수',
        '소도구 트레이닝 교육 이수',
      ],
      images: [trainer5_1, trainer5_2],
    },
    {
      id: 6,
      name: '황태현 트레이너',
      career: [
        '남스짐 1호점 트레이너',
        '전) 운동하자 트레이너',
        '전) 스타일바디 트레이너',
      ],
      tags: [
        '생활스포츠지도사 2급(보디빌딩)',
        'CES PERSONAL TRAINING',
        'Functional Taping 자격증',
        'NASM CPT',
        '글라스톤 교육 이수',
        '스포츠 마사지 교육 이수',
        '소도구 트레이닝 교육 이수',
      ],
      images: [trainer6_1],
    },
    {
      id: 7,
      name: '이재정 트레이너',
      career: [
        '남스짐 1호점 마스터 트레이너',
        '전) 메이드핏 트레이너',
        '전) 3GYM 트레이너',
        '21` 무사 수원 PCA보디빌딩 은메달',
        '20` PCA 보디빌딩 은메달',
        '19` 미스터 수원 은메달',
        '19` 미스터 화성 은메달',
        '18` 미스터 인천 동메달',
        '17` 미스터 시흥 출전',
      ],
      tags: [
        '생활스포츠지도사 2급(보디빌딩)',
        'Functional Taping 자격증',
        '케틀벨&TRX 교육 이수',
        '글라스톤 교육 이수',
        '스포츠 마사지 교육 이수',
        '소도구 트레이닝 교육 이수',
      ],
      images: [trainer7_1],
    },
    {
      id: 8,
      name: '임예본 트레이너',
      career: ['남스짐 1호점 트레이너'],
      tags: [
        '생활스포츠지도사 2급(보디빌딩)',
        'Functional Taping 자격증',
        '케틀벨&TRX 교육 이수',
        '글라스톤 교육 이수',
        '스포츠 마사지 교육 이수',
        '소도구 트레이닝 교육 이수',
      ],
      images: [trainer8_1, trainer8_2],
    },
    {
      id: 9,
      name: '장영환 트레이너',
      career: ['남스짐 1호점 트레이너'],
      tags: [
        '생활스포츠지도사 2급(보디빌딩)',
        'Functional Taping 자격증',
        '케틀벨&TRX 교육 이수',
        '글라스톤 교육 이수',
        '스포츠 마사지 교육 이수',
        '소도구 트레이닝 교육 이수',
      ],
      images: [trainer9_1, trainer9_2],
    },
  ],
  kakaoTalkUrl: 'https://pf.kakao.com/_FxgHWd',
  naverPlaceUrl: 'https://naver.me/x4bOeUXv',
};

export default center1;
