import {
  center1_1,
  center1_2,
  center1_3,
  center1_4,
  trainer1_1_1,
  trainer1_2_1,
  trainer1_3_1,
  trainer1_4_1,
  trainer1_5_1,
  trainer1_6_1,
  trainer1_7_1,
} from '@/public/png/center/center1/index';

const center1 = {
  centerName: '7호점 안산 고잔점',
  address: '안산시 단원구 원고잔로 17',
  phone: '010-0000-0000',
  images: [center1_1, center1_2, center1_3, center1_4],
  operatingTime: '06:00 ~ 24:00',
  trainers: [
    {
      id: 1,
      name: '김현정 트레이너',
      tags: [
        '생활체육지도자 2급(보디빌딩)',
        'BLACK ROLL 자격증',
        'TFT 자격증',
        '소도구 트레이닝 교육 이수',
        'FISAF KOREA 자격증',
        'Functional Taping 자격증',
      ],
      images: [trainer1_1_1],
    },
    {
      id: 2,
      name: '손석환 트레이너',
      tags: [
        '생활체육지도자 2급(보디빌딩)',
        '스포츠 마사지 교육 이수',
        '소도구 트레이닝 교육 이수',
        'FISAF KOREA 자격증',
        'Functional Taping 자격증',
      ],
      images: [trainer1_2_1],
    },
    {
      id: 3,
      name: '김지훈 트레이너',
      tags: [
        '생활체육지도자 2급(보디빌딩)',
        'FISAF KOREA PERSONAL TRAINING',
        'FISAF KOREA MEDICAL TRAINING',
        'CES KOREA 대한교정운동전문가',
        'KT TAPE 자격',
        'AKF KETTLEBELL LEVEL 1,2,3',
        'NASM CPT',
        'WNGP 보디빌딩 동메달',
        '글라스톤 교육 이수',
        '스포츠 마사지 교육 이수',
        '소도구 트레이닝 교육 이수',
      ],
      images: [trainer1_3_1],
    },
    {
      id: 4,
      name: '황재민 트레이너',
      tags: [
        '생활체육지도자 2급(보디빌딩)',
        '명지대학교 체육학부 졸업',
        'FISAF KOREA PERSONAL TRAINING',
        'FISAF KOREA MEDICAL TRAINING',
        'CES KOREA 교정운동학',
        'KT TAPE 자격',
        'AKF KETTLEBELL LEVEL 1,2,3',
        'WNGP 주최 대회 스포츠모델 TOP 6',
        '글라스톤 교육 이수',
      ],
      images: [trainer1_4_1],
    },
    {
      id: 5,
      name: '박지희 트레이너',
      tags: [
        '생활체육지도자 2급(보디빌딩)',
        '관동대학교 사회체육학과 졸업',
        'CES PERSONAL TRAINING',
        'NASM CPT',
        '유아체육지도자',
        '운동처방사',
        'KT TAPE 자격',
        '글라스톤 교육 이수',
        '스포츠 마사지 교육 이수',
        '소도구 트레이닝 교육 이수',
      ],
      images: [trainer1_5_1],
    },
    {
      id: 6,
      name: '황태현 트레이너',
      tags: [
        '생활체육지도자 2급(보디빌딩)',
        'CES PERSONAL TRAINING',
        'Functional Taping 자격증',
        'NASM CPT',
        '글라스톤 교육 이수',
        '스포츠 마사지 교육 이수',
        '소도구 트레이닝 교육 이수',
      ],
      images: [trainer1_6_1],
    },
    {
      id: 7,
      name: '이재정 트레이너',
      tags: [
        '생활체육지도자 2급(보디빌딩)',
        'Functional Taping 자격증',
        '케틀벨&TRX 교육 이수',
        '글라스톤 교육 이수',
        '스포츠 마사지 교육 이수',
        '소도구 트레이닝 교육 이수',
      ],
      images: [trainer1_7_1],
    },
  ],
  kakaoTalkUrl: 'https://pf.kakao.com/_FxgHWd',
  blogUrl: 'https://blog.naver.com/namsgym',
};

export default center1;
